### ISSUE TITLE
Failed to install 'cordova-plugin-ezar-videooverlay'

### ISSUE THREAD

**Issue by Md-Sadham** [ezartech/ezar-facedetector#5]
When adding android platform to this project then am facing below issues:

....
Installing "cordova-plugin-ezar-videooverlay" for android
Failed to install 'cordova-plugin-ezar-videooverlay': Error: ENOENT: no such file or directory, open 'D:\Projects\ezar-facedetector-master\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (D:\Projects\ezar-facedetector-master\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (D:\Projects\ezar-facedetector-master\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (D:\Projects\ezar-facedetector-master\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (D:\Projects\ezar-facedetector-master\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\sadham.hussain\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\sadham.hussain\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\sadham.hussain\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\sadham.hussain\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
Failed to restore plugin "cordova-plugin-ezar-videooverlay" from config.xml. You might need to try adding it again. Error: Error: ENOENT: no such file or directory, open 'D:\Projects\ezar-facedetector-master\platforms\android\AndroidManifest.xml'
--save flag or autosave detected
Saving android@~7.0.0 into config.xml file ...

**Comment by Md-Sadham** [comment]
Resolved by below steps:
1. After extract the zip and open the projects in Vs Code.
2. I download the Video overlay plugin separately from wayneparrott GitHub page.
3. I was added the video overlay plugin before adding the android platform. Those process are done through commands without any error and warnings.
