### ISSUE TITLE
cp: copyFileSync: could not write to dest file

### ISSUE THREAD

**Issue by Md-Sadham** [ezartech/ezar-facedetector#6]
After extracting your project, first add the video overlay plugin through command successfully. Then I added the android platform through command successfully without any errors and warnings. After that, I try to build the app and facing below issues. 

Please help me for resolving it! Thanks!

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS D:\TestProjects\CordovaProjects\ezar-facedetector-master> cordova build android
cp: copyFileSync: could not write to dest file (code=ENOENT):D:\TestProjects\CordovaProjects\ezar-facedetector-master\platforms\android\res\xml\config.xml

Parsing D:\TestProjects\CordovaProjects\ezar-facedetector-master\platforms\android\res\xml\config.xml failed
(node:13836) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'D:\TestProjects\CordovaProjects\ezar-facedetector-master\platforms\android\res\xml\config.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (D:\TestProjects\CordovaProjects\ezar-facedetector-master\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new ConfigParser (D:\TestProjects\CordovaProjects\ezar-facedetector-master\platforms\android\cordova\node_modules\cordova-common\src\ConfigParser\ConfigParser.js:30:24)
    at updateConfigFilesFrom (D:\TestProjects\CordovaProjects\ezar-facedetector-master\platforms\android\cordova\lib\prepare.js:106:18)
    at Api.module.exports.prepare (D:\TestProjects\CordovaProjects\ezar-facedetector-master\platforms\android\cordova\lib\prepare.js:42:20)
    at Api.prepare (D:\TestProjects\CordovaProjects\ezar-facedetector-master\platforms\android\cordova\Api.js:192:45)
    at C:\Users\sadham.hussain\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:106:36
    at _fulfilled (C:\Users\sadham.hussain\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\sadham.hussain\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
(node:13836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled
will terminate the Node.js process with a non-zero exit code.

PS D:\TestProjects\CordovaProjects\ezar-facedetector-master> cordova plugin -ls
cordova-plugin-ezar-facedetector 1.0.0 "ezAR Face Detector Plugin"
cordova-plugin-ezar-snapshot 1.0.0 "ezAR Snapshot"
cordova-plugin-ezar-videooverlay 1.0.0 "ezAR Video Overlay Plugin"
cordova-plugin-whitelist 1.3.3 "Whitelist"
PS D:\TestProjects\CordovaProjects\ezar-facedetector-master> cordova platform -ls
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

**Comment by Md-Sadham** [comment]
Resolved by below steps:

1. Add patch-android-studio-check.js file in the hook folder. File Path: https://gist.github.com/joeljeske/68121fa6d643e0937f50458d0172e16e

2. Add the following lines to the config.xml of your project:
<platform name="android">
    <hook src="hooks/patch-android-studio-check.js" type="before_plugin_install" />
    <hook src="hooks/patch-android-studio-check.js" type="before_plugin_add" />
    <hook src="hooks/patch-android-studio-check.js" type="before_build" />
    <hook src="hooks/patch-android-studio-check.js" type="before_run" />
    <hook src="hooks/patch-android-studio-check.js" type="before_plugin_rm" />
</platform>

Those points are enough for my environment to run this awesome project.

References:
https://stackoverflow.com/questions/48006196/ionic-build-androids-error-copyfilesync-could-not-write-to-dest-file
